#!/usr/bin/env ruby

require "rubygems"
require "bundler/setup"
require "optparse"
require "fileutils"
require "mini_magick"
require_relative "../lib/picture"

DEF_SIZE = -"400x400>"
SUB_DIRS = [Picture::WEB_SUBDIR, Picture::THUMB_SUBDIR].freeze
IMG_QUALITY = 80
THREADS = 4

options = {}
OptionParser.new do |opts|
  opts.banner = "Usage: #{File.join(__dir__, __FILE__)} [options]"

  opts.on("-d", "--directory=DIRECTORY", "Pictures directory") do |dir|
    options[:pic_dir] = dir
  end

  opts.on("-s", "--thumb-size=SIZE", "Thumbnails size (default #{DEF_SIZE})") do |size|
    options[:thumb_size] = size
  end

  opts.on("-f", "--force", "Override existing thumbnails") do |f|
    options[:force] = f
  end
end.parse!

public_dir = Pathname(options.fetch(:pic_dir, Picture::PUBLIC_DIR)).expand_path
public_dir.children.select(&:directory?).each do |folder|
  SUB_DIRS.each do |sub_dir|
    folder.join(sub_dir).mkpath
  end
end

thumb_size = options.fetch(:thumb_size, DEF_SIZE)
thumb_size << -">" unless thumb_size.end_with?(-">")

Picture::EXTENSIONS.each do |ext|
  if options[:force]
    SUB_DIRS.each do |sub_dir|
      FileUtils.rm_f(Dir[public_dir.join("*", sub_dir, "*.#{ext}")])
    end
  end

  pic_paths = Dir[public_dir.join("*", "*.#{ext}")]
  queue = pic_paths.inject(Queue.new) { |q, path| q << Pathname(path) }

  (1..[queue.size, THREADS].min).map {
    Thread.new do
      img_src_path = begin
                       queue.pop(true)
                     rescue ThreadError; end

      while img_src_path
        img_bname = img_src_path.basename

        img_web_path = img_src_path.dirname.join(Picture::WEB_SUBDIR, img_bname)
        if options[:force] || !File.exist?(img_web_path)
          image = MiniMagick::Image.open(img_src_path)
          image.quality(IMG_QUALITY)
          image.write(img_web_path)
        end

        img_thumb_path = img_src_path.dirname.join(Picture::THUMB_SUBDIR, img_bname)
        if options[:force] || !File.exist?(img_thumb_path)
          image = MiniMagick::Image.open(img_src_path)
          image.combine_options do |c|
            c.thumbnail(thumb_size)
            c.quality(IMG_QUALITY)
          end
          image.write(img_thumb_path)
        end

        img_src_path = begin
                         queue.pop(true)
                       rescue ThreadError; end
      end
    end
  }.each(&:join)
end
